### ISSUE TITLE
支持AEAD加密算法

### ISSUE THREAD

**Issue by POJOa** [0312birdzhang/jolla-settings-gost-button#2]
因为上游gost的原因，该项目不支持AEAD加密，这点很可惜...
我现在想用ss-libev，给配个界面，尽管没有qt的开发经验...大概也许不会太麻烦吧...

凑合的话也可以build一下ss-libev，现在openrepos上的版本太旧，也不支持AEAD...
然后我发现大佬当时似乎是在OBS上自动build的...

然而OBS的账号申请麻烦，bugzilla要邮箱手工验证，我发了邮件，不知道要多久才能过...
大佬方便再build一版造福全人类吗...

**Comment by 0312birdzhang** [comment]
https://build.merproject.org/package/show/home:birdzhang/shadowsocks-libev 各种缺，，，

**Comment by POJOa** [comment]
omfg......

**Comment by 0312birdzhang** [comment]
@POJOa 已编译完成 https://build.merproject.org/package/show/home:birdzhang/shadowsocks-libev

**Comment by 0312birdzhang** [comment]
好像执行的时候有问题，先不要装

**Comment by 0312birdzhang** [comment]
修复了，可以测试一下 https://openrepos.net/content/birdzhang/shadowsocks-libev

**Comment by 0312birdzhang** [comment]
已上传到openrepost https://openrepos.net/content/birdzhang/shadowsocks-libev
目测是没有问题了

**Comment by POJOa** [comment]
辛苦大佬了。。。

**Comment by 0312birdzhang** [comment]
没问题的话这个issue关了
